//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: MDFTicker.proto
namespace MDFTicker
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"MdfTicker")]
  public partial class MdfTicker : global::ProtoBuf.IExtensible
  {
    public MdfTicker() {}
    
    private string _symbol;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private string _updateTime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"updateTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string updateTime
    {
      get { return _updateTime; }
      set { _updateTime = value; }
    }
    private double _bid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double bid
    {
      get { return _bid; }
      set { _bid = value; }
    }
    private double _ask;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"ask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double ask
    {
      get { return _ask; }
      set { _ask = value; }
    }

    private double _last = default(double);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"last", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double last
    {
      get { return _last; }
      set { _last = value; }
    }

    private double _open = default(double);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"open", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double open
    {
      get { return _open; }
      set { _open = value; }
    }

    private double _high = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"high", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double high
    {
      get { return _high; }
      set { _high = value; }
    }

    private double _low = default(double);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"low", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double low
    {
      get { return _low; }
      set { _low = value; }
    }

    private int _vol = default(int);
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"vol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int vol
    {
      get { return _vol; }
      set { _vol = value; }
    }

    private int _openInterest = default(int);
    [global::ProtoBuf.ProtoMember(10, IsRequired = false, Name=@"openInterest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int openInterest
    {
      get { return _openInterest; }
      set { _openInterest = value; }
    }

    private int _bidvol = default(int);
    [global::ProtoBuf.ProtoMember(11, IsRequired = false, Name=@"bidvol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bidvol
    {
      get { return _bidvol; }
      set { _bidvol = value; }
    }

    private int _askvol = default(int);
    [global::ProtoBuf.ProtoMember(12, IsRequired = false, Name=@"askvol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int askvol
    {
      get { return _askvol; }
      set { _askvol = value; }
    }

    private double _bid2 = default(double);
    [global::ProtoBuf.ProtoMember(13, IsRequired = false, Name=@"bid2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double bid2
    {
      get { return _bid2; }
      set { _bid2 = value; }
    }

    private double _ask2 = default(double);
    [global::ProtoBuf.ProtoMember(14, IsRequired = false, Name=@"ask2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double ask2
    {
      get { return _ask2; }
      set { _ask2 = value; }
    }

    private double _bid3 = default(double);
    [global::ProtoBuf.ProtoMember(15, IsRequired = false, Name=@"bid3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double bid3
    {
      get { return _bid3; }
      set { _bid3 = value; }
    }

    private double _ask3 = default(double);
    [global::ProtoBuf.ProtoMember(16, IsRequired = false, Name=@"ask3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double ask3
    {
      get { return _ask3; }
      set { _ask3 = value; }
    }

    private double _bid4 = default(double);
    [global::ProtoBuf.ProtoMember(17, IsRequired = false, Name=@"bid4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double bid4
    {
      get { return _bid4; }
      set { _bid4 = value; }
    }

    private double _ask4 = default(double);
    [global::ProtoBuf.ProtoMember(18, IsRequired = false, Name=@"ask4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double ask4
    {
      get { return _ask4; }
      set { _ask4 = value; }
    }

    private double _bid5 = default(double);
    [global::ProtoBuf.ProtoMember(19, IsRequired = false, Name=@"bid5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double bid5
    {
      get { return _bid5; }
      set { _bid5 = value; }
    }

    private double _ask5 = default(double);
    [global::ProtoBuf.ProtoMember(20, IsRequired = false, Name=@"ask5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double ask5
    {
      get { return _ask5; }
      set { _ask5 = value; }
    }

    private int _bidVol2 = default(int);
    [global::ProtoBuf.ProtoMember(21, IsRequired = false, Name=@"bidVol2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bidVol2
    {
      get { return _bidVol2; }
      set { _bidVol2 = value; }
    }

    private int _askVol2 = default(int);
    [global::ProtoBuf.ProtoMember(22, IsRequired = false, Name=@"askVol2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int askVol2
    {
      get { return _askVol2; }
      set { _askVol2 = value; }
    }

    private int _bidVol3 = default(int);
    [global::ProtoBuf.ProtoMember(23, IsRequired = false, Name=@"bidVol3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bidVol3
    {
      get { return _bidVol3; }
      set { _bidVol3 = value; }
    }

    private int _askVol3 = default(int);
    [global::ProtoBuf.ProtoMember(24, IsRequired = false, Name=@"askVol3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int askVol3
    {
      get { return _askVol3; }
      set { _askVol3 = value; }
    }

    private int _bidVol4 = default(int);
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"bidVol4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bidVol4
    {
      get { return _bidVol4; }
      set { _bidVol4 = value; }
    }

    private int _askVol4 = default(int);
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"askVol4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int askVol4
    {
      get { return _askVol4; }
      set { _askVol4 = value; }
    }

    private int _bidVol5 = default(int);
    [global::ProtoBuf.ProtoMember(27, IsRequired = false, Name=@"bidVol5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int bidVol5
    {
      get { return _bidVol5; }
      set { _bidVol5 = value; }
    }

    private int _askVol5 = default(int);
    [global::ProtoBuf.ProtoMember(28, IsRequired = false, Name=@"askVol5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int askVol5
    {
      get { return _askVol5; }
      set { _askVol5 = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}