//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: order_easy.proto
namespace order_easy
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"order_record")]
  public partial class order_record : global::ProtoBuf.IExtensible
  {
    public order_record() {}
    
    private int _local_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"local_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int local_ref
    {
      get { return _local_ref; }
      set { _local_ref = value; }
    }
    private string _symbol;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private int _price_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"price_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price_type
    {
      get { return _price_type; }
      set { _price_type = value; }
    }
    private double _price;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double price
    {
      get { return _price; }
      set { _price = value; }
    }
    private int _vol;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"vol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vol
    {
      get { return _vol; }
      set { _vol = value; }
    }
    private int _dir;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private int _order_ref;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"order_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order_ref
    {
      get { return _order_ref; }
      set { _order_ref = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"login_req")]
  public partial class login_req : global::ProtoBuf.IExtensible
  {
    public login_req() {}
    
    private string _version;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"version", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string version
    {
      get { return _version; }
      set { _version = value; }
    }
    private string _account;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _symbol;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private double _symbol_tip;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"symbol_tip", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double symbol_tip
    {
      get { return _symbol_tip; }
      set { _symbol_tip = value; }
    }

    private int _exchange_type = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"exchange_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int exchange_type
    {
      get { return _exchange_type; }
      set { _exchange_type = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"login_resp")]
  public partial class login_resp : global::ProtoBuf.IExtensible
  {
    public login_resp() {}
    
    private string _symbol;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private int _success;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"success", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int success
    {
      get { return _success; }
      set { _success = value; }
    }
    private int _last_local_ref;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"last_local_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int last_local_ref
    {
      get { return _last_local_ref; }
      set { _last_local_ref = value; }
    }
    private int _long_pos;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"long_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int long_pos
    {
      get { return _long_pos; }
      set { _long_pos = value; }
    }
    private int _short_pos;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"short_pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int short_pos
    {
      get { return _short_pos; }
      set { _short_pos = value; }
    }
    private readonly global::System.Collections.Generic.List<order_easy.order_record> _order_list = new global::System.Collections.Generic.List<order_easy.order_record>();
    [global::ProtoBuf.ProtoMember(6, Name=@"order_list", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<order_easy.order_record> order_list
    {
      get { return _order_list; }
    }
  

    private string _ErrorMsg = "";
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"ErrorMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrorMsg
    {
      get { return _ErrorMsg; }
      set { _ErrorMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"order_req")]
  public partial class order_req : global::ProtoBuf.IExtensible
  {
    public order_req() {}
    
    private int _local_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"local_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int local_ref
    {
      get { return _local_ref; }
      set { _local_ref = value; }
    }
    private string _symbol;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private int _price_type;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"price_type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int price_type
    {
      get { return _price_type; }
      set { _price_type = value; }
    }
    private double _price;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double price
    {
      get { return _price; }
      set { _price = value; }
    }
    private int _vol;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"vol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vol
    {
      get { return _vol; }
      set { _vol = value; }
    }
    private int _dir;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"order_resp")]
  public partial class order_resp : global::ProtoBuf.IExtensible
  {
    public order_resp() {}
    
    private int _local_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"local_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int local_ref
    {
      get { return _local_ref; }
      set { _local_ref = value; }
    }
    private int _order_ref;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"order_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order_ref
    {
      get { return _order_ref; }
      set { _order_ref = value; }
    }
    private string _tick_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tick_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tick_time
    {
      get { return _tick_time; }
      set { _tick_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"order_resp_err")]
  public partial class order_resp_err : global::ProtoBuf.IExtensible
  {
    public order_resp_err() {}
    
    private int _local_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"local_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int local_ref
    {
      get { return _local_ref; }
      set { _local_ref = value; }
    }
    private string _tick_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tick_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tick_time
    {
      get { return _tick_time; }
      set { _tick_time = value; }
    }
    private string _error_msg;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"error_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string error_msg
    {
      get { return _error_msg; }
      set { _error_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cancel_req")]
  public partial class cancel_req : global::ProtoBuf.IExtensible
  {
    public cancel_req() {}
    
    private int _local_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"local_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int local_ref
    {
      get { return _local_ref; }
      set { _local_ref = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cancel_resp")]
  public partial class cancel_resp : global::ProtoBuf.IExtensible
  {
    public cancel_resp() {}
    
    private int _local_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"local_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int local_ref
    {
      get { return _local_ref; }
      set { _local_ref = value; }
    }
    private int _order_ref;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"order_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order_ref
    {
      get { return _order_ref; }
      set { _order_ref = value; }
    }
    private string _tick_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tick_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tick_time
    {
      get { return _tick_time; }
      set { _tick_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"cancel_resp_err")]
  public partial class cancel_resp_err : global::ProtoBuf.IExtensible
  {
    public cancel_resp_err() {}
    
    private int _local_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"local_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int local_ref
    {
      get { return _local_ref; }
      set { _local_ref = value; }
    }
    private int _order_ref;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"order_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int order_ref
    {
      get { return _order_ref; }
      set { _order_ref = value; }
    }
    private string _tick_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tick_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tick_time
    {
      get { return _tick_time; }
      set { _tick_time = value; }
    }
    private string _error_msg;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"error_msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string error_msg
    {
      get { return _error_msg; }
      set { _error_msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"delete_rtn")]
  public partial class delete_rtn : global::ProtoBuf.IExtensible
  {
    public delete_rtn() {}
    
    private int _local_ref;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"local_ref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int local_ref
    {
      get { return _local_ref; }
      set { _local_ref = value; }
    }
    private string _tick_time;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"tick_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tick_time
    {
      get { return _tick_time; }
      set { _tick_time = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"pos_rtn")]
  public partial class pos_rtn : global::ProtoBuf.IExtensible
  {
    public pos_rtn() {}
    
    private string _tick_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tick_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tick_time
    {
      get { return _tick_time; }
      set { _tick_time = value; }
    }
    private string _symbol;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private int _dir;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private int _vol;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"vol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vol
    {
      get { return _vol; }
      set { _vol = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"message_rtn")]
  public partial class message_rtn : global::ProtoBuf.IExtensible
  {
    public message_rtn() {}
    
    private string _tick_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tick_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tick_time
    {
      get { return _tick_time; }
      set { _tick_time = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"force_logout_rtn")]
  public partial class force_logout_rtn : global::ProtoBuf.IExtensible
  {
    public force_logout_rtn() {}
    
    private string _tick_time;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"tick_time", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string tick_time
    {
      get { return _tick_time; }
      set { _tick_time = value; }
    }
    private string _msg;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"msg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string msg
    {
      get { return _msg; }
      set { _msg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}