//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: RcXSpeedMdfPack.proto
namespace RcXSpeedMdfPack
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tick_TenEntrust")]
  public partial class Tick_TenEntrust : global::ProtoBuf.IExtensible
  {
    public Tick_TenEntrust() {}
    
    private string _symbol;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private string _updatetime;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"updatetime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string updatetime
    {
      get { return _updatetime; }
      set { _updatetime = value; }
    }
    private double _best_bid;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"best_bid", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double best_bid
    {
      get { return _best_bid; }
      set { _best_bid = value; }
    }
    private int _best_bid_qty1;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"best_bid_qty1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty1
    {
      get { return _best_bid_qty1; }
      set { _best_bid_qty1 = value; }
    }
    private int _best_bid_qty2;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"best_bid_qty2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty2
    {
      get { return _best_bid_qty2; }
      set { _best_bid_qty2 = value; }
    }
    private int _best_bid_qty3;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"best_bid_qty3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty3
    {
      get { return _best_bid_qty3; }
      set { _best_bid_qty3 = value; }
    }
    private int _best_bid_qty4;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"best_bid_qty4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty4
    {
      get { return _best_bid_qty4; }
      set { _best_bid_qty4 = value; }
    }
    private int _best_bid_qty5;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"best_bid_qty5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty5
    {
      get { return _best_bid_qty5; }
      set { _best_bid_qty5 = value; }
    }
    private int _best_bid_qty6;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"best_bid_qty6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty6
    {
      get { return _best_bid_qty6; }
      set { _best_bid_qty6 = value; }
    }
    private int _best_bid_qty7;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"best_bid_qty7", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty7
    {
      get { return _best_bid_qty7; }
      set { _best_bid_qty7 = value; }
    }
    private int _best_bid_qty8;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"best_bid_qty8", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty8
    {
      get { return _best_bid_qty8; }
      set { _best_bid_qty8 = value; }
    }
    private int _best_bid_qty9;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"best_bid_qty9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty9
    {
      get { return _best_bid_qty9; }
      set { _best_bid_qty9 = value; }
    }
    private int _best_bid_qty10;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"best_bid_qty10", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_bid_qty10
    {
      get { return _best_bid_qty10; }
      set { _best_bid_qty10 = value; }
    }
    private double _best_ask;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"best_ask", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double best_ask
    {
      get { return _best_ask; }
      set { _best_ask = value; }
    }
    private int _best_ask_qty1;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"best_ask_qty1", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty1
    {
      get { return _best_ask_qty1; }
      set { _best_ask_qty1 = value; }
    }
    private int _best_ask_qty2;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"best_ask_qty2", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty2
    {
      get { return _best_ask_qty2; }
      set { _best_ask_qty2 = value; }
    }
    private int _best_ask_qty3;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"best_ask_qty3", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty3
    {
      get { return _best_ask_qty3; }
      set { _best_ask_qty3 = value; }
    }
    private int _best_ask_qty4;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"best_ask_qty4", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty4
    {
      get { return _best_ask_qty4; }
      set { _best_ask_qty4 = value; }
    }
    private int _best_ask_qty5;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"best_ask_qty5", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty5
    {
      get { return _best_ask_qty5; }
      set { _best_ask_qty5 = value; }
    }
    private int _best_ask_qty6;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"best_ask_qty6", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty6
    {
      get { return _best_ask_qty6; }
      set { _best_ask_qty6 = value; }
    }
    private int _best_ask_qty7;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"best_ask_qty7", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty7
    {
      get { return _best_ask_qty7; }
      set { _best_ask_qty7 = value; }
    }
    private int _best_ask_qty8;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"best_ask_qty8", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty8
    {
      get { return _best_ask_qty8; }
      set { _best_ask_qty8 = value; }
    }
    private int _best_ask_qty9;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"best_ask_qty9", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty9
    {
      get { return _best_ask_qty9; }
      set { _best_ask_qty9 = value; }
    }
    private int _best_ask_qty10;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"best_ask_qty10", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int best_ask_qty10
    {
      get { return _best_ask_qty10; }
      set { _best_ask_qty10 = value; }
    }

    private string _Type = "";
    [global::ProtoBuf.ProtoMember(25, IsRequired = false, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string Type
    {
      get { return _Type; }
      set { _Type = value; }
    }

    private string _tradingday = "";
    [global::ProtoBuf.ProtoMember(26, IsRequired = false, Name=@"tradingday", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string tradingday
    {
      get { return _tradingday; }
      set { _tradingday = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tick_BestAndDeep")]
  public partial class Tick_BestAndDeep : global::ProtoBuf.IExtensible
  {
    public Tick_BestAndDeep() {}
    
    private int _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _Length;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Length", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Length
    {
      get { return _Length; }
      set { _Length = value; }
    }
    private int _Version;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"Version", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Version
    {
      get { return _Version; }
      set { _Version = value; }
    }
    private int _Time;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"Time", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Time
    {
      get { return _Time; }
      set { _Time = value; }
    }
    private string _Exchange;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"Exchange", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Exchange
    {
      get { return _Exchange; }
      set { _Exchange = value; }
    }
    private string _Contract;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"Contract", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string Contract
    {
      get { return _Contract; }
      set { _Contract = value; }
    }
    private int _SuspensionSign;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"SuspensionSign", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SuspensionSign
    {
      get { return _SuspensionSign; }
      set { _SuspensionSign = value; }
    }
    private double _LastClearPrice;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"LastClearPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double LastClearPrice
    {
      get { return _LastClearPrice; }
      set { _LastClearPrice = value; }
    }
    private double _ClearPrice;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"ClearPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double ClearPrice
    {
      get { return _ClearPrice; }
      set { _ClearPrice = value; }
    }
    private double _AvgPrice;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"AvgPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double AvgPrice
    {
      get { return _AvgPrice; }
      set { _AvgPrice = value; }
    }
    private double _LastClose;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"LastClose", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double LastClose
    {
      get { return _LastClose; }
      set { _LastClose = value; }
    }
    private double _Close;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"Close", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Close
    {
      get { return _Close; }
      set { _Close = value; }
    }
    private double _OpenPrice;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"OpenPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double OpenPrice
    {
      get { return _OpenPrice; }
      set { _OpenPrice = value; }
    }
    private int _LastOpenInterest;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"LastOpenInterest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int LastOpenInterest
    {
      get { return _LastOpenInterest; }
      set { _LastOpenInterest = value; }
    }
    private int _OpenInterest;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"OpenInterest", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int OpenInterest
    {
      get { return _OpenInterest; }
      set { _OpenInterest = value; }
    }
    private double _LastPrice;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"LastPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double LastPrice
    {
      get { return _LastPrice; }
      set { _LastPrice = value; }
    }
    private int _MatchTotQty;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"MatchTotQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int MatchTotQty
    {
      get { return _MatchTotQty; }
      set { _MatchTotQty = value; }
    }
    private double _Turnover;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"Turnover", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Turnover
    {
      get { return _Turnover; }
      set { _Turnover = value; }
    }
    private double _RiseLimit;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"RiseLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double RiseLimit
    {
      get { return _RiseLimit; }
      set { _RiseLimit = value; }
    }
    private double _FallLimit;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"FallLimit", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double FallLimit
    {
      get { return _FallLimit; }
      set { _FallLimit = value; }
    }
    private double _HighPrice;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"HighPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double HighPrice
    {
      get { return _HighPrice; }
      set { _HighPrice = value; }
    }
    private double _LowPrice;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"LowPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double LowPrice
    {
      get { return _LowPrice; }
      set { _LowPrice = value; }
    }
    private double _PreDelta;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"PreDelta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double PreDelta
    {
      get { return _PreDelta; }
      set { _PreDelta = value; }
    }
    private double _CurrDelta;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"CurrDelta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double CurrDelta
    {
      get { return _CurrDelta; }
      set { _CurrDelta = value; }
    }
    private double _BuyPriceOne;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"BuyPriceOne", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double BuyPriceOne
    {
      get { return _BuyPriceOne; }
      set { _BuyPriceOne = value; }
    }
    private int _BuyQtyOne;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"BuyQtyOne", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyQtyOne
    {
      get { return _BuyQtyOne; }
      set { _BuyQtyOne = value; }
    }
    private int _BuyImplyQtyOne;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"BuyImplyQtyOne", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyImplyQtyOne
    {
      get { return _BuyImplyQtyOne; }
      set { _BuyImplyQtyOne = value; }
    }
    private double _BuyPriceTwo;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"BuyPriceTwo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double BuyPriceTwo
    {
      get { return _BuyPriceTwo; }
      set { _BuyPriceTwo = value; }
    }
    private int _BuyQtyTwo;
    [global::ProtoBuf.ProtoMember(29, IsRequired = true, Name=@"BuyQtyTwo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyQtyTwo
    {
      get { return _BuyQtyTwo; }
      set { _BuyQtyTwo = value; }
    }
    private int _BuyImplyQtyTwo;
    [global::ProtoBuf.ProtoMember(30, IsRequired = true, Name=@"BuyImplyQtyTwo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyImplyQtyTwo
    {
      get { return _BuyImplyQtyTwo; }
      set { _BuyImplyQtyTwo = value; }
    }
    private double _BuyPriceThree;
    [global::ProtoBuf.ProtoMember(31, IsRequired = true, Name=@"BuyPriceThree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double BuyPriceThree
    {
      get { return _BuyPriceThree; }
      set { _BuyPriceThree = value; }
    }
    private int _BuyQtyThree;
    [global::ProtoBuf.ProtoMember(32, IsRequired = true, Name=@"BuyQtyThree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyQtyThree
    {
      get { return _BuyQtyThree; }
      set { _BuyQtyThree = value; }
    }
    private int _BuyImplyQtyThree;
    [global::ProtoBuf.ProtoMember(33, IsRequired = true, Name=@"BuyImplyQtyThree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyImplyQtyThree
    {
      get { return _BuyImplyQtyThree; }
      set { _BuyImplyQtyThree = value; }
    }
    private double _BuyPriceFour;
    [global::ProtoBuf.ProtoMember(34, IsRequired = true, Name=@"BuyPriceFour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double BuyPriceFour
    {
      get { return _BuyPriceFour; }
      set { _BuyPriceFour = value; }
    }
    private int _BuyQtyFour;
    [global::ProtoBuf.ProtoMember(35, IsRequired = true, Name=@"BuyQtyFour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyQtyFour
    {
      get { return _BuyQtyFour; }
      set { _BuyQtyFour = value; }
    }
    private int _BuyImplyQtyFour;
    [global::ProtoBuf.ProtoMember(36, IsRequired = true, Name=@"BuyImplyQtyFour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyImplyQtyFour
    {
      get { return _BuyImplyQtyFour; }
      set { _BuyImplyQtyFour = value; }
    }
    private double _BuyPriceFive;
    [global::ProtoBuf.ProtoMember(37, IsRequired = true, Name=@"BuyPriceFive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double BuyPriceFive
    {
      get { return _BuyPriceFive; }
      set { _BuyPriceFive = value; }
    }
    private int _BuyQtyFive;
    [global::ProtoBuf.ProtoMember(38, IsRequired = true, Name=@"BuyQtyFive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyQtyFive
    {
      get { return _BuyQtyFive; }
      set { _BuyQtyFive = value; }
    }
    private int _BuyImplyQtyFive;
    [global::ProtoBuf.ProtoMember(39, IsRequired = true, Name=@"BuyImplyQtyFive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int BuyImplyQtyFive
    {
      get { return _BuyImplyQtyFive; }
      set { _BuyImplyQtyFive = value; }
    }
    private double _SellPriceOne;
    [global::ProtoBuf.ProtoMember(40, IsRequired = true, Name=@"SellPriceOne", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double SellPriceOne
    {
      get { return _SellPriceOne; }
      set { _SellPriceOne = value; }
    }
    private int _SellQtyOne;
    [global::ProtoBuf.ProtoMember(41, IsRequired = true, Name=@"SellQtyOne", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellQtyOne
    {
      get { return _SellQtyOne; }
      set { _SellQtyOne = value; }
    }
    private int _SellImplyQtyOne;
    [global::ProtoBuf.ProtoMember(42, IsRequired = true, Name=@"SellImplyQtyOne", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellImplyQtyOne
    {
      get { return _SellImplyQtyOne; }
      set { _SellImplyQtyOne = value; }
    }
    private double _SellPriceTwo;
    [global::ProtoBuf.ProtoMember(43, IsRequired = true, Name=@"SellPriceTwo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double SellPriceTwo
    {
      get { return _SellPriceTwo; }
      set { _SellPriceTwo = value; }
    }
    private int _SellQtyTwo;
    [global::ProtoBuf.ProtoMember(44, IsRequired = true, Name=@"SellQtyTwo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellQtyTwo
    {
      get { return _SellQtyTwo; }
      set { _SellQtyTwo = value; }
    }
    private int _SellImplyQtyTwo;
    [global::ProtoBuf.ProtoMember(45, IsRequired = true, Name=@"SellImplyQtyTwo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellImplyQtyTwo
    {
      get { return _SellImplyQtyTwo; }
      set { _SellImplyQtyTwo = value; }
    }
    private double _SellPriceThree;
    [global::ProtoBuf.ProtoMember(46, IsRequired = true, Name=@"SellPriceThree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double SellPriceThree
    {
      get { return _SellPriceThree; }
      set { _SellPriceThree = value; }
    }
    private int _SellQtyThree;
    [global::ProtoBuf.ProtoMember(47, IsRequired = true, Name=@"SellQtyThree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellQtyThree
    {
      get { return _SellQtyThree; }
      set { _SellQtyThree = value; }
    }
    private int _SellImplyQtyThree;
    [global::ProtoBuf.ProtoMember(48, IsRequired = true, Name=@"SellImplyQtyThree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellImplyQtyThree
    {
      get { return _SellImplyQtyThree; }
      set { _SellImplyQtyThree = value; }
    }
    private double _SellPriceFour;
    [global::ProtoBuf.ProtoMember(49, IsRequired = true, Name=@"SellPriceFour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double SellPriceFour
    {
      get { return _SellPriceFour; }
      set { _SellPriceFour = value; }
    }
    private int _SellQtyFour;
    [global::ProtoBuf.ProtoMember(50, IsRequired = true, Name=@"SellQtyFour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellQtyFour
    {
      get { return _SellQtyFour; }
      set { _SellQtyFour = value; }
    }
    private int _SellImplyQtyFour;
    [global::ProtoBuf.ProtoMember(51, IsRequired = true, Name=@"SellImplyQtyFour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellImplyQtyFour
    {
      get { return _SellImplyQtyFour; }
      set { _SellImplyQtyFour = value; }
    }
    private double _SellPriceFive;
    [global::ProtoBuf.ProtoMember(52, IsRequired = true, Name=@"SellPriceFive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double SellPriceFive
    {
      get { return _SellPriceFive; }
      set { _SellPriceFive = value; }
    }
    private int _SellQtyFive;
    [global::ProtoBuf.ProtoMember(53, IsRequired = true, Name=@"SellQtyFive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellQtyFive
    {
      get { return _SellQtyFive; }
      set { _SellQtyFive = value; }
    }
    private int _SellImplyQtyFive;
    [global::ProtoBuf.ProtoMember(54, IsRequired = true, Name=@"SellImplyQtyFive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int SellImplyQtyFive
    {
      get { return _SellImplyQtyFive; }
      set { _SellImplyQtyFive = value; }
    }
    private string _GenTime;
    [global::ProtoBuf.ProtoMember(55, IsRequired = true, Name=@"GenTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string GenTime
    {
      get { return _GenTime; }
      set { _GenTime = value; }
    }
    private int _LastMatchQty;
    [global::ProtoBuf.ProtoMember(56, IsRequired = true, Name=@"LastMatchQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int LastMatchQty
    {
      get { return _LastMatchQty; }
      set { _LastMatchQty = value; }
    }
    private int _InterestChg;
    [global::ProtoBuf.ProtoMember(57, IsRequired = true, Name=@"InterestChg", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int InterestChg
    {
      get { return _InterestChg; }
      set { _InterestChg = value; }
    }
    private double _LifeLow;
    [global::ProtoBuf.ProtoMember(58, IsRequired = true, Name=@"LifeLow", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double LifeLow
    {
      get { return _LifeLow; }
      set { _LifeLow = value; }
    }
    private double _LifeHigh;
    [global::ProtoBuf.ProtoMember(59, IsRequired = true, Name=@"LifeHigh", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double LifeHigh
    {
      get { return _LifeHigh; }
      set { _LifeHigh = value; }
    }
    private double _Delta;
    [global::ProtoBuf.ProtoMember(60, IsRequired = true, Name=@"Delta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Delta
    {
      get { return _Delta; }
      set { _Delta = value; }
    }
    private double _Gamma;
    [global::ProtoBuf.ProtoMember(61, IsRequired = true, Name=@"Gamma", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Gamma
    {
      get { return _Gamma; }
      set { _Gamma = value; }
    }
    private double _Rho;
    [global::ProtoBuf.ProtoMember(62, IsRequired = true, Name=@"Rho", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Rho
    {
      get { return _Rho; }
      set { _Rho = value; }
    }
    private double _Theta;
    [global::ProtoBuf.ProtoMember(63, IsRequired = true, Name=@"Theta", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Theta
    {
      get { return _Theta; }
      set { _Theta = value; }
    }
    private double _Vega;
    [global::ProtoBuf.ProtoMember(64, IsRequired = true, Name=@"Vega", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double Vega
    {
      get { return _Vega; }
      set { _Vega = value; }
    }
    private string _TradeDate;
    [global::ProtoBuf.ProtoMember(65, IsRequired = true, Name=@"TradeDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string TradeDate
    {
      get { return _TradeDate; }
      set { _TradeDate = value; }
    }
    private string _LocalDate;
    [global::ProtoBuf.ProtoMember(66, IsRequired = true, Name=@"LocalDate", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string LocalDate
    {
      get { return _LocalDate; }
      set { _LocalDate = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tick_RealTimePrice")]
  public partial class Tick_RealTimePrice : global::ProtoBuf.IExtensible
  {
    public Tick_RealTimePrice() {}
    
    private int _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _Len;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Len", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Len
    {
      get { return _Len; }
      set { _Len = value; }
    }
    private string _ContractID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ContractID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ContractID
    {
      get { return _ContractID; }
      set { _ContractID = value; }
    }
    private double _RealTimePrice;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"RealTimePrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double RealTimePrice
    {
      get { return _RealTimePrice; }
      set { _RealTimePrice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tick_OrderStatistic")]
  public partial class Tick_OrderStatistic : global::ProtoBuf.IExtensible
  {
    public Tick_OrderStatistic() {}
    
    private int _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _Len;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Len", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Len
    {
      get { return _Len; }
      set { _Len = value; }
    }
    private string _ContractID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ContractID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ContractID
    {
      get { return _ContractID; }
      set { _ContractID = value; }
    }
    private int _TotalBuyOrderNum;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"TotalBuyOrderNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TotalBuyOrderNum
    {
      get { return _TotalBuyOrderNum; }
      set { _TotalBuyOrderNum = value; }
    }
    private int _TotalSellOrderNum;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"TotalSellOrderNum", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int TotalSellOrderNum
    {
      get { return _TotalSellOrderNum; }
      set { _TotalSellOrderNum = value; }
    }
    private double _WeightedAverageBuyOrderPrice;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"WeightedAverageBuyOrderPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double WeightedAverageBuyOrderPrice
    {
      get { return _WeightedAverageBuyOrderPrice; }
      set { _WeightedAverageBuyOrderPrice = value; }
    }
    private double _WeightedAverageSellOrderPrice;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"WeightedAverageSellOrderPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double WeightedAverageSellOrderPrice
    {
      get { return _WeightedAverageSellOrderPrice; }
      set { _WeightedAverageSellOrderPrice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Tick_MarchPriceQty")]
  public partial class Tick_MarchPriceQty : global::ProtoBuf.IExtensible
  {
    public Tick_MarchPriceQty() {}
    
    private int _Type;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"Type", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Type
    {
      get { return _Type; }
      set { _Type = value; }
    }
    private int _Len;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"Len", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int Len
    {
      get { return _Len; }
      set { _Len = value; }
    }
    private string _ContractID;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"ContractID", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string ContractID
    {
      get { return _ContractID; }
      set { _ContractID = value; }
    }
    private double _PriceOne;
    [global::ProtoBuf.ProtoMember(4, IsRequired = true, Name=@"PriceOne", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double PriceOne
    {
      get { return _PriceOne; }
      set { _PriceOne = value; }
    }
    private int _PriceOneBOQty;
    [global::ProtoBuf.ProtoMember(5, IsRequired = true, Name=@"PriceOneBOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceOneBOQty
    {
      get { return _PriceOneBOQty; }
      set { _PriceOneBOQty = value; }
    }
    private int _PriceOneBEQty;
    [global::ProtoBuf.ProtoMember(6, IsRequired = true, Name=@"PriceOneBEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceOneBEQty
    {
      get { return _PriceOneBEQty; }
      set { _PriceOneBEQty = value; }
    }
    private int _PriceOneSOQty;
    [global::ProtoBuf.ProtoMember(7, IsRequired = true, Name=@"PriceOneSOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceOneSOQty
    {
      get { return _PriceOneSOQty; }
      set { _PriceOneSOQty = value; }
    }
    private int _PriceOneSEQty;
    [global::ProtoBuf.ProtoMember(8, IsRequired = true, Name=@"PriceOneSEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceOneSEQty
    {
      get { return _PriceOneSEQty; }
      set { _PriceOneSEQty = value; }
    }
    private double _PriceTwo;
    [global::ProtoBuf.ProtoMember(9, IsRequired = true, Name=@"PriceTwo", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double PriceTwo
    {
      get { return _PriceTwo; }
      set { _PriceTwo = value; }
    }
    private int _PriceTwoBOQty;
    [global::ProtoBuf.ProtoMember(10, IsRequired = true, Name=@"PriceTwoBOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceTwoBOQty
    {
      get { return _PriceTwoBOQty; }
      set { _PriceTwoBOQty = value; }
    }
    private int _PriceTwoBEQty;
    [global::ProtoBuf.ProtoMember(11, IsRequired = true, Name=@"PriceTwoBEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceTwoBEQty
    {
      get { return _PriceTwoBEQty; }
      set { _PriceTwoBEQty = value; }
    }
    private int _PriceTwoSOQty;
    [global::ProtoBuf.ProtoMember(12, IsRequired = true, Name=@"PriceTwoSOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceTwoSOQty
    {
      get { return _PriceTwoSOQty; }
      set { _PriceTwoSOQty = value; }
    }
    private int _PriceTwoSEQty;
    [global::ProtoBuf.ProtoMember(13, IsRequired = true, Name=@"PriceTwoSEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceTwoSEQty
    {
      get { return _PriceTwoSEQty; }
      set { _PriceTwoSEQty = value; }
    }
    private double _PriceThree;
    [global::ProtoBuf.ProtoMember(14, IsRequired = true, Name=@"PriceThree", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double PriceThree
    {
      get { return _PriceThree; }
      set { _PriceThree = value; }
    }
    private int _PriceThreeBOQty;
    [global::ProtoBuf.ProtoMember(15, IsRequired = true, Name=@"PriceThreeBOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceThreeBOQty
    {
      get { return _PriceThreeBOQty; }
      set { _PriceThreeBOQty = value; }
    }
    private int _PriceThreeBEQty;
    [global::ProtoBuf.ProtoMember(16, IsRequired = true, Name=@"PriceThreeBEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceThreeBEQty
    {
      get { return _PriceThreeBEQty; }
      set { _PriceThreeBEQty = value; }
    }
    private int _PriceThreeSOQty;
    [global::ProtoBuf.ProtoMember(17, IsRequired = true, Name=@"PriceThreeSOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceThreeSOQty
    {
      get { return _PriceThreeSOQty; }
      set { _PriceThreeSOQty = value; }
    }
    private int _PriceThreeSEQty;
    [global::ProtoBuf.ProtoMember(18, IsRequired = true, Name=@"PriceThreeSEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceThreeSEQty
    {
      get { return _PriceThreeSEQty; }
      set { _PriceThreeSEQty = value; }
    }
    private double _PriceFour;
    [global::ProtoBuf.ProtoMember(19, IsRequired = true, Name=@"PriceFour", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double PriceFour
    {
      get { return _PriceFour; }
      set { _PriceFour = value; }
    }
    private int _PriceFourBOQty;
    [global::ProtoBuf.ProtoMember(20, IsRequired = true, Name=@"PriceFourBOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceFourBOQty
    {
      get { return _PriceFourBOQty; }
      set { _PriceFourBOQty = value; }
    }
    private int _PriceFourBEQty;
    [global::ProtoBuf.ProtoMember(21, IsRequired = true, Name=@"PriceFourBEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceFourBEQty
    {
      get { return _PriceFourBEQty; }
      set { _PriceFourBEQty = value; }
    }
    private int _PriceFourSOQty;
    [global::ProtoBuf.ProtoMember(22, IsRequired = true, Name=@"PriceFourSOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceFourSOQty
    {
      get { return _PriceFourSOQty; }
      set { _PriceFourSOQty = value; }
    }
    private int _PriceFourSEQty;
    [global::ProtoBuf.ProtoMember(23, IsRequired = true, Name=@"PriceFourSEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceFourSEQty
    {
      get { return _PriceFourSEQty; }
      set { _PriceFourSEQty = value; }
    }
    private double _PriceFive;
    [global::ProtoBuf.ProtoMember(24, IsRequired = true, Name=@"PriceFive", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double PriceFive
    {
      get { return _PriceFive; }
      set { _PriceFive = value; }
    }
    private int _PriceFiveBOQty;
    [global::ProtoBuf.ProtoMember(25, IsRequired = true, Name=@"PriceFiveBOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceFiveBOQty
    {
      get { return _PriceFiveBOQty; }
      set { _PriceFiveBOQty = value; }
    }
    private int _PriceFiveBEQty;
    [global::ProtoBuf.ProtoMember(26, IsRequired = true, Name=@"PriceFiveBEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceFiveBEQty
    {
      get { return _PriceFiveBEQty; }
      set { _PriceFiveBEQty = value; }
    }
    private int _PriceFiveSOQty;
    [global::ProtoBuf.ProtoMember(27, IsRequired = true, Name=@"PriceFiveSOQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceFiveSOQty
    {
      get { return _PriceFiveSOQty; }
      set { _PriceFiveSOQty = value; }
    }
    private int _PriceFiveSEQty;
    [global::ProtoBuf.ProtoMember(28, IsRequired = true, Name=@"PriceFiveSEQty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int PriceFiveSEQty
    {
      get { return _PriceFiveSEQty; }
      set { _PriceFiveSEQty = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}