//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from: OrderEasy_data.proto
namespace OrderEasy.common
{
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderEasy_data")]
  public partial class OrderEasy_data : global::ProtoBuf.IExtensible
  {
    public OrderEasy_data() {}
    
    private OrderEasy_data.REQType _reqType;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"reqType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public OrderEasy_data.REQType reqType
    {
      get { return _reqType; }
      set { _reqType = value; }
    }

    private OrderEasy_data.OrderREQ _orderReq = null;
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"orderReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OrderEasy_data.OrderREQ orderReq
    {
      get { return _orderReq; }
      set { _orderReq = value; }
    }

    private OrderEasy_data.OrderRESP _orderResp = null;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"orderResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OrderEasy_data.OrderRESP orderResp
    {
      get { return _orderResp; }
      set { _orderResp = value; }
    }

    private OrderEasy_data.CancelREQ _cancelReq = null;
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"cancelReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OrderEasy_data.CancelREQ cancelReq
    {
      get { return _cancelReq; }
      set { _cancelReq = value; }
    }

    private OrderEasy_data.CancelRESP _cancelResp = null;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"cancelResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OrderEasy_data.CancelRESP cancelResp
    {
      get { return _cancelResp; }
      set { _cancelResp = value; }
    }

    private OrderEasy_data.InitREQ _initReq = null;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"initReq", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OrderEasy_data.InitREQ initReq
    {
      get { return _initReq; }
      set { _initReq = value; }
    }

    private OrderEasy_data.InitRESP _initResp = null;
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"initResp", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue(null)]
    public OrderEasy_data.InitRESP initResp
    {
      get { return _initResp; }
      set { _initResp = value; }
    }
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderREQ")]
  public partial class OrderREQ : global::ProtoBuf.IExtensible
  {
    public OrderREQ() {}
    
    private string _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private string _symbol;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private OrderEasy_data.OrderType _orderType;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"orderType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public OrderEasy_data.OrderType orderType
    {
      get { return _orderType; }
      set { _orderType = value; }
    }

    private double _price = default(double);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double price
    {
      get { return _price; }
      set { _price = value; }
    }

    private int _qty = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"qty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int qty
    {
      get { return _qty; }
      set { _qty = value; }
    }

    private OrderEasy_data.Direction _dir = OrderEasy_data.Direction.buy;
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(OrderEasy_data.Direction.buy)]
    public OrderEasy_data.Direction dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private readonly global::System.Collections.Generic.List<OrderEasy_data.Strategy> _strat = new global::System.Collections.Generic.List<OrderEasy_data.Strategy>();
    [global::ProtoBuf.ProtoMember(7, Name=@"strat", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<OrderEasy_data.Strategy> strat
    {
      get { return _strat; }
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"OrderRESP")]
  public partial class OrderRESP : global::ProtoBuf.IExtensible
  {
    public OrderRESP() {}
    
    private int _ErrorID;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"ErrorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ErrorID
    {
      get { return _ErrorID; }
      set { _ErrorID = value; }
    }

    private string _ErrorMsg = "";
    [global::ProtoBuf.ProtoMember(2, IsRequired = false, Name=@"ErrorMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrorMsg
    {
      get { return _ErrorMsg; }
      set { _ErrorMsg = value; }
    }

    private int _orderref = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"orderref", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int orderref
    {
      get { return _orderref; }
      set { _orderref = value; }
    }

    private string _orderTime = "";
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"orderTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string orderTime
    {
      get { return _orderTime; }
      set { _orderTime = value; }
    }

    private OrderEasy_data.E_x _e_x = OrderEasy_data.E_x.Exit;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"e_x", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(OrderEasy_data.E_x.Exit)]
    public OrderEasy_data.E_x e_x
    {
      get { return _e_x; }
      set { _e_x = value; }
    }

    private int _qty = default(int);
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"qty", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int qty
    {
      get { return _qty; }
      set { _qty = value; }
    }

    private double _price = default(double);
    [global::ProtoBuf.ProtoMember(7, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double price
    {
      get { return _price; }
      set { _price = value; }
    }

    private int _notCloseVol = default(int);
    [global::ProtoBuf.ProtoMember(8, IsRequired = false, Name=@"notCloseVol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int notCloseVol
    {
      get { return _notCloseVol; }
      set { _notCloseVol = value; }
    }

    private OrderEasy_data.PosStatus _pos = OrderEasy_data.PosStatus.Long;
    [global::ProtoBuf.ProtoMember(9, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(OrderEasy_data.PosStatus.Long)]
    public OrderEasy_data.PosStatus pos
    {
      get { return _pos; }
      set { _pos = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelREQ")]
  public partial class CancelREQ : global::ProtoBuf.IExtensible
  {
    public CancelREQ() {}
    
    private string _symbol;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private OrderEasy_data.CancelType _cancelType;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"cancelType", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public OrderEasy_data.CancelType cancelType
    {
      get { return _cancelType; }
      set { _cancelType = value; }
    }

    private OrderEasy_data.Direction _dir = OrderEasy_data.Direction.buy;
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"dir", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(OrderEasy_data.Direction.buy)]
    public OrderEasy_data.Direction dir
    {
      get { return _dir; }
      set { _dir = value; }
    }
    private readonly global::System.Collections.Generic.List<string> _guid = new global::System.Collections.Generic.List<string>();
    [global::ProtoBuf.ProtoMember(4, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public global::System.Collections.Generic.List<string> guid
    {
      get { return _guid; }
    }
  

    private double _price = default(double);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"price", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(double))]
    public double price
    {
      get { return _price; }
      set { _price = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"CancelRESP")]
  public partial class CancelRESP : global::ProtoBuf.IExtensible
  {
    public CancelRESP() {}
    
    private string _guid;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"guid", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string guid
    {
      get { return _guid; }
      set { _guid = value; }
    }
    private int _ErrorID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ErrorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ErrorID
    {
      get { return _ErrorID; }
      set { _ErrorID = value; }
    }

    private string _cancelTime = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"cancelTime", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string cancelTime
    {
      get { return _cancelTime; }
      set { _cancelTime = value; }
    }

    private int _notCloseVol = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"notCloseVol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int notCloseVol
    {
      get { return _notCloseVol; }
      set { _notCloseVol = value; }
    }

    private OrderEasy_data.PosStatus _pos = OrderEasy_data.PosStatus.Long;
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"pos", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(OrderEasy_data.PosStatus.Long)]
    public OrderEasy_data.PosStatus pos
    {
      get { return _pos; }
      set { _pos = value; }
    }

    private string _ErrorMsg = "";
    [global::ProtoBuf.ProtoMember(6, IsRequired = false, Name=@"ErrorMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrorMsg
    {
      get { return _ErrorMsg; }
      set { _ErrorMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitREQ")]
  public partial class InitREQ : global::ProtoBuf.IExtensible
  {
    public InitREQ() {}
    
    private string _account;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"account", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string account
    {
      get { return _account; }
      set { _account = value; }
    }
    private string _symbol;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }

    private int _maxVol = default(int);
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"maxVol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int maxVol
    {
      get { return _maxVol; }
      set { _maxVol = value; }
    }

    private int _stopLoss = default(int);
    [global::ProtoBuf.ProtoMember(4, IsRequired = false, Name=@"stopLoss", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int stopLoss
    {
      get { return _stopLoss; }
      set { _stopLoss = value; }
    }

    private int _profigTarget = default(int);
    [global::ProtoBuf.ProtoMember(5, IsRequired = false, Name=@"profigTarget", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    [global::System.ComponentModel.DefaultValue(default(int))]
    public int profigTarget
    {
      get { return _profigTarget; }
      set { _profigTarget = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"InitRESP")]
  public partial class InitRESP : global::ProtoBuf.IExtensible
  {
    public InitRESP() {}
    
    private string _symbol;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"symbol", DataFormat = global::ProtoBuf.DataFormat.Default)]
    public string symbol
    {
      get { return _symbol; }
      set { _symbol = value; }
    }
    private int _ErrorID;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"ErrorID", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int ErrorID
    {
      get { return _ErrorID; }
      set { _ErrorID = value; }
    }

    private string _ErrorMsg = "";
    [global::ProtoBuf.ProtoMember(3, IsRequired = false, Name=@"ErrorMsg", DataFormat = global::ProtoBuf.DataFormat.Default)]
    [global::System.ComponentModel.DefaultValue("")]
    public string ErrorMsg
    {
      get { return _ErrorMsg; }
      set { _ErrorMsg = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
  [global::System.Serializable, global::ProtoBuf.ProtoContract(Name=@"Strategy")]
  public partial class Strategy : global::ProtoBuf.IExtensible
  {
    public Strategy() {}
    
    private int _vol;
    [global::ProtoBuf.ProtoMember(1, IsRequired = true, Name=@"vol", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public int vol
    {
      get { return _vol; }
      set { _vol = value; }
    }
    private double _maxPrice;
    [global::ProtoBuf.ProtoMember(2, IsRequired = true, Name=@"maxPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double maxPrice
    {
      get { return _maxPrice; }
      set { _maxPrice = value; }
    }
    private double _minPrice;
    [global::ProtoBuf.ProtoMember(3, IsRequired = true, Name=@"minPrice", DataFormat = global::ProtoBuf.DataFormat.TwosComplement)]
    public double minPrice
    {
      get { return _minPrice; }
      set { _minPrice = value; }
    }
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
    [global::ProtoBuf.ProtoContract(Name=@"REQType")]
    public enum REQType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"init", Value=0)]
      init = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"order", Value=1)]
      order = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"close", Value=2)]
      close = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"cancel", Value=3)]
      cancel = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"Direction")]
    public enum Direction
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"buy", Value=0)]
      buy = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"sell", Value=1)]
      sell = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"PosStatus")]
    public enum PosStatus
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Long", Value=0)]
      Long = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Short", Value=1)]
      Short = 1
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"OrderType")]
    public enum OrderType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"limit", Value=0)]
      limit = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"market", Value=1)]
      market = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"rev", Value=2)]
      rev = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"strat", Value=3)]
      strat = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"CancelType")]
    public enum CancelType
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"cancelOne", Value=0)]
      cancelOne = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"cancelMarket", Value=1)]
      cancelMarket = 1,
            
      [global::ProtoBuf.ProtoEnum(Name=@"cancelAll", Value=2)]
      cancelAll = 2,
            
      [global::ProtoBuf.ProtoEnum(Name=@"cancelStrategy", Value=3)]
      cancelStrategy = 3
    }
  
    [global::ProtoBuf.ProtoContract(Name=@"E_x")]
    public enum E_x
    {
            
      [global::ProtoBuf.ProtoEnum(Name=@"Exit", Value=0)]
      Exit = 0,
            
      [global::ProtoBuf.ProtoEnum(Name=@"Entry", Value=1)]
      Entry = 1
    }
  
    private global::ProtoBuf.IExtension extensionObject;
    global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
      { return global::ProtoBuf.Extensible.GetExtensionObject(ref extensionObject, createIfMissing); }
  }
  
}